typedef enum _fieldtypes {
    FIELD_FLOAT, FIELD_STRING, FIELD_ENTITY, FIELD_CLASSPTR, FIELD_EHANDLE, FIELD_EVARS, 
    FIELD_EDICT, FIELD_VECTOR, FIELD_POSITION_VECTOR, FIELD_POINTER, FIELD_INTEGER, FIELD_FUNCTION, 
    FIELD_BOOLEAN, FIELD_SHORT, FIELD_CHARACTER, FIELD_TIME, FIELD_MODELNAME, FIELD_SOUNDNAME, FIELD_TYPECOUNT
}FIELDTYPE;