struct frame_t {
    double receivedtime;
    double latency;
    qboolean invalid;
    qboolean choked;
    entity_state_s playerstate[32];
    double time;
    clientdata_t clientdata;
    weapon_data_s weapondata[64];
    packet_entities_t packet_entities;
    unsigned short clientbytes;
    unsigned short playerinfobytes;
    unsigned short packetentitybytes;
    unsigned short tentitybytes;
    unsigned short soundbytes;
    unsigned short eventbytes;
    unsigned short usrbytes;
    unsigned short voicebytes;
    unsigned short msgbytes;
};