typedef struct physent_s {
    char name[32];
    int player;
    vec3_t origin;
    model_s *model;
    model_s *studiomodel;
    vec3_t mins;
    vec3_t maxs;
    int info;
    vec3_t angles;
    int solid;
    int skin;
    int rendermode;
    float frame;
    int sequence;
    unsigned char controller[4];
    unsigned char blending[2];
    int movetype;
    int takedamage;
    int blooddecal;
    int team;
    int classnumber;
    int iuser1;
    int iuser2;
    int iuser3;
    int iuser4;
    float fuser1;
    float fuser2;
    float fuser3;
    float fuser4;
    vec3_t vuser1;
    vec3_t vuser2;
    vec3_t vuser3;
    vec3_t vuser4;
} physent_t;