typedef struct playermove_s {
    int player_index;
    qboolean server;
    qboolean multiplayer;
    float time;
    float frametime;
    vec3_t forward;
    vec3_t right;
    vec3_t up;
    vec3_t origin;
    vec3_t angles;
    vec3_t oldangles;
    vec3_t velocity;
    vec3_t movedir;
    vec3_t basevelocity;
    vec3_t view_ofs;
    float flDuckTime;
    qboolean bInDuck;
    int flTimeStepSound;
    int iStepLeft;
    float flFallVelocity;
    vec3_t punchangle;
    float flSwimTime;
    float flNextPrimaryAttack;
    int effects;
    int flags;
    int usehull;
    float gravity;
    float friction;
    int oldbuttons;
    float waterjumptime;
    qboolean dead;
    int deadflag;
    int spectator;
    int movetype;
    int onground;
    int waterlevel;
    int watertype;
    int oldwaterlevel;
    char sztexturename[256];
    char chtexturetype;
    float maxspeed;
    float clientmaxspeed;
    int iuser1;
    int iuser2;
    int iuser3;
    int iuser4;
    float fuser1;
    float fuser2;
    float fuser3;
    float fuser4;
    vec3_t vuser1;
    vec3_t vuser2;
    vec3_t vuser3;
    vec3_t vuser4;
    int numphysent;
    physent_t physents[600];
    int nummoveent;
    physent_t moveents[64];
    int numvisent;
    physent_t visents[600];
    usercmd_t cmd;
    int numtouch;
    pmtrace_t touchindex[600];
    char physinfo[256];
    movevars_s *movevars;
    vec_t player_mins[4][3];
    vec_t player_maxs[4][3];
    const char *(*PM_Info_ValueForKey)(const char *, const char *);
    void (*PM_Particle)(float *, int, float, int, int);
    int (*PM_TestPlayerPosition)(float *, pmtrace_t *);
    void (*Con_NPrintf)(int, char *, ...);
    void (*Con_DPrintf)(char *, ...);
    void (*Con_Printf)(char *, ...);
    double (*Sys_FloatTime)(void);
    void (*PM_StuckTouch)(int, pmtrace_t *);
    int (*PM_PointContents)(float *, int *);
    int (*PM_TruePointContents)(float *);
    int (*PM_HullPointContents)(hull_s *, int, float *);
    pmtrace_t (*PM_PlayerTrace)(float *, float *, int, int);
    pmtrace_s *(*PM_TraceLine)(float *, float *, int, int, int);
    int32 (*RandomLong)(int32, int32);
    float (*RandomFloat)(float, float);
    int (*PM_GetModelType)(model_s *);
    void (*PM_GetModelBounds)(model_s *, float *, float *);
    void *(*PM_HullForBsp)(physent_t *, float *);
    float (*PM_TraceModel)(physent_t *, float *, float *, trace_t *);
    int (*COM_FileSize)(char *);
    byte *(*COM_LoadFile)(char *, int, int *);
    void (*COM_FreeFile)(void *);
    char *(*memfgets)(byte *, int, int *, char *, int);
    qboolean runfuncs;
    void (*PM_PlaySound)(int, const char *, float, float, int, int);
    const char *(*PM_TraceTexture)(int, float *, float *);
    void (*PM_PlaybackEventFull)(int, int, unsigned short, float, float *, float *, float, float, int, int, int, int);
    pmtrace_t (*PM_PlayerTraceEx)(float *, float *, int, int (*)(physent_t *));
    int (*PM_TestPlayerPositionEx)(float *, pmtrace_t *, int (*)(physent_t *));
    pmtrace_s *(*PM_TraceLineEx)(float *, float *, int, int, int (*)(physent_t *));
} playermove_t;