#define IN_ATTACK	 (1 << 0)
#define IN_JUMP		 (1 << 1)
#define IN_DUCK		 (1 << 2)
#define IN_FORWARD	 (1 << 3)
#define IN_BACK		 (1 << 4)
#define IN_USE		 (1 << 5)
#define IN_CANCEL	 (1 << 6)
#define IN_LEFT		 (1 << 7)
#define IN_RIGHT	 (1 << 8)
#define IN_MOVELEFT	 (1 << 9)
#define IN_MOVERIGHT (1 << 10)
#define IN_ATTACK2	 (1 << 11)
#define IN_RUN       (1 << 12)
#define IN_RELOAD	 (1 << 13)
#define IN_ALT1		 (1 << 14)
#define IN_SCORE	 (1 << 15)

#define	FL_FLY					(1<<0)
#define	FL_SWIM					(1<<1)
#define	FL_CONVEYOR				(1<<2)
#define	FL_CLIENT				(1<<3)
#define	FL_INWATER				(1<<4)
#define	FL_MONSTER				(1<<5)
#define	FL_GODMODE				(1<<6)
#define	FL_NOTARGET				(1<<7)
#define	FL_SKIPLOCALHOST		(1<<8)
#define	FL_ONGROUND				(1<<9)
#define	FL_PARTIALGROUND		(1<<10)
#define	FL_WATERJUMP			(1<<11)
#define FL_FROZEN				(1<<12)
#define FL_FAKECLIENT			(1<<13)
#define FL_DUCKING				(1<<14)
#define FL_FLOAT				(1<<15)
#define FL_GRAPHED				(1<<16)
#define FL_IMMUNE_WATER			(1<<17)
#define	FL_IMMUNE_SLIME			(1<<18)
#define FL_IMMUNE_LAVA			(1<<19)
#define FL_PROXY				(1<<20)
#define FL_ALWAYSTHINK			(1<<21)
#define FL_BASEVELOCITY			(1<<22)
#define FL_MONSTERCLIP			(1<<23)
#define FL_ONTRAIN				(1<<24)
#define FL_WORLDBRUSH			(1<<25)
#define FL_SPECTATOR            (1<<26)
#define FL_CUSTOMENTITY			(1<<29)
#define FL_KILLME				(1<<30)
#define FL_DORMANT				(1<<31)